let variable = 10;
console.log("valor inicial:");
console.log(variable);
variable = 20;
console.log("cambio 1:");
console.log(variable);
variable = 30;
console.log("cambio 2:");
console.log(variable);
const constante = 50;
